working_hours_works:
    resource: "@WorkingHoursBundle/Controller/WorksController.php"
    type:     annotation

working_hours_projects:
    resource: "@WorkingHoursBundle/Controller/ProjectsController.php"
    type:     annotation

working_hours_categories:
    resource: "@WorkingHoursBundle/Controller/CategoriesController.php"
    type:     annotation
    
working_hours_users:
    resource: "@WorkingHoursBundle/Controller/UserController.php"
    type:     annotation

working_hours:
    resource: "@WorkingHoursBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"